# Generated by Django 4.2.8 on 2023-12-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("CountryId", models.AutoField(primary_key=True, serialize=False)),
                ("CountryFlag", models.CharField(default="N/A", max_length=10)),
                ("CountryCode", models.CharField(max_length=100)),
                ("CountryName", models.CharField(max_length=100)),
                ("CountryRank", models.IntegerField(default=-1)),
                ("CountryConf", models.CharField(default="N/A", max_length=100)),
            ],
        ),
    ]
